<?php

return [
    'mod_system_Adsense' => \ImpressCMS\Modules\System\Models\Adsense::class,
    'mod_system_AdsenseHandler' => \ImpressCMS\Modules\System\Models\AdsenseHandler::class,
    'mod_system_Autotasks'=>\ImpressCMS\Modules\System\Models\Autotask::class,
    'mod_system_AutotasksHandler'=>\ImpressCMS\Modules\System\Models\AutotaskHandler::class,
    'mod_system_AvatarsHandler'=>\ImpressCMS\Modules\System\Models\AvatarHandler::class,
    'mod_system_Blocks'=>\ImpressCMS\Modules\System\Models\Block::class,
    'mod_system_BlocksHandler'=>\ImpressCMS\Modules\System\Models\BlockHandler::class,
    'mod_system_CommentsHandler'=>\ImpressCMS\Modules\System\Models\CommentHandler::class,
    'mod_system_Customtag'=>\ImpressCMS\Modules\System\Models\CustomTag::class,
    'mod_system_CustomtagHandler'=>\ImpressCMS\Modules\System\Models\CustomTagHandler::class,
    'mod_system_GroupsHandler'=>\ImpressCMS\Modules\System\Models\GroupHandler::class,
    'mod_system_ImagesHandler'=>\ImpressCMS\Modules\System\Models\ImageHandler::class,
    'mod_system_ModulesHandler'=>\ImpressCMS\Modules\System\Models\ModuleHandler::class,
    'mod_system_Pages'=>\ImpressCMS\Modules\System\Models\Page::class,
    'mod_system_PagesHandler'=>\ImpressCMS\Modules\System\Models\PageHandler::class,
    'mod_system_Positions'=>\ImpressCMS\Modules\System\Models\BlockPosition::class,
    'mod_system_PositionsHandler'=>\ImpressCMS\Modules\System\Models\BlockPositionHandler::class,
    'mod_system_Rating'=>\ImpressCMS\Modules\System\Models\Rating::class,
    'mod_system_RatingHandler'=>\ImpressCMS\Modules\System\Models\RatingHandler::class,
    'mod_system_SmiliesHandler'=>\ImpressCMS\Modules\System\Models\SmileHandler::class,
    'mod_system_Tags'=>\ImpressCMS\Modules\System\Models\Tag::class,
    'mod_system_TagsHandler'=>\ImpressCMS\Modules\System\Models\TagHandler::class,
    'mod_system_TplsetsHandler'=>\ImpressCMS\Modules\System\Models\TemplateSetHandler::class,
    'mod_system_Userrank'=>\ImpressCMS\Modules\System\Models\UserRank::class,
    'mod_system_UserrankHandler'=>\ImpressCMS\Modules\System\Models\UserRankHandler::class,
    'mod_system_UsersHandler'=>\ImpressCMS\Modules\System\Models\UserHandler::class,
];